require 'application_system_test_case'

# validations on user
# 5  <= name.length  <= 50
# 10 <= email.length <= 100 & regex
# 8  <= password.length
# password = confirmation

class UsersTest < ApplicationSystemTestCase
  def setup
    @my_driver = self.class.driver
  end

  # test 'equivalence partitioning testing register' do
  #   # equivalence classes:
  #   # name_1 = 5..50
  #   # name_2 = {name.length < 5}
  #   # name_3 = {name.length > 50}
  #   #
  #   # email_1 = {10..100} -> formated
  #   # email_2 = {email.length < 10} -> formated
  #   # email_3 = {email.length > 100} -> formated
  #   # email_4 = {10..100} -> not formated
  #   # email_5 = {email.length < 10} -> not formated
  #   # email_6 = {email.length > 100} -> not formated
  #   #
  #   # password_1 = {password.length >= 8}
  #   # password_2 = {password.length < 8}
  #   #
  #   # confirmation_1 = {passwords match}
  #   # confirmation_2 = {passwords don't match}
  #   #
  #   # email_valid:
  #   # 'aaaaaa@a.a'
  #   tests_valid_user_created = [
  #     {name: 'a' * 10, email: 'a' * 10 + '@b.a', password: 'a' * 10, confirmation: 'a' * 10}
  #   ]
  #   tests_invalid_user_not_created = [
  #     {name:  'a' * 10, email:  'a' * 10 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 10 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 10, email:  'a' * 10 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 2 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 10, email:  'a' * 2 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 2 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 10, email:  'a' * 2 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 101 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 10, email:  'a' * 101 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 101 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 10, email:  'a' * 101 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 10 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 10, email:  'a' * 10 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 10 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 10, email:  'a' * 10 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 2 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 10, email:  'a' * 2 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 2 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 10, email:  'a' * 2 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 101 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 10, email:  'a' * 101 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 10, email:  'a' * 101 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 10, email:  'a' * 101 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 10 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 2, email:  'a' * 10 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 10 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 2, email:  'a' * 10 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 2 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 2, email:  'a' * 2 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 2 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 2, email:  'a' * 2 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 101 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 2, email:  'a' * 101 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 101 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 2, email:  'a' * 101 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 10 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 2, email:  'a' * 10 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 10 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 2, email:  'a' * 10 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 2 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 2, email:  'a' * 2 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 2 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 2, email:  'a' * 2 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 101 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 2, email:  'a' * 101 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 2, email:  'a' * 101 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 2, email:  'a' * 101 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 10 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 55, email:  'a' * 10 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 10 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 55, email:  'a' * 10 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 2 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 55, email:  'a' * 2 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 2 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 55, email:  'a' * 2 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 101 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 55, email:  'a' * 101 + '@a.a', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 101 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 55, email:  'a' * 101 + '@a.a', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 10 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 55, email:  'a' * 10 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 10 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 55, email:  'a' * 10 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 2 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 55, email:  'a' * 2 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 2 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 55, email:  'a' * 2 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 101 + '@aa', password:  'a' * 10, confirmation:  'a' * 10},
  #     {name:  'a' * 55, email:  'a' * 101 + '@aa', password:  'a' * 10, confirmation:  'a' * 10 + 'a'},
  #     {name:  'a' * 55, email:  'a' * 101 + '@aa', password:  'a' * 3, confirmation:  'a' * 3},
  #     {name:  'a' * 55, email:  'a' * 101 + '@aa', password:  'a' * 3, confirmation:  'a' * 3 + 'a'},
  #   ]
  #   tests_valid_user_created.each do |test|
  #     visit signup_path
  #     fill_in "Name", with: test[:name]
  #     fill_in "Email", with: test[:email]
  #     fill_in "Password", with: test[:password]
  #     fill_in "Confirmation", with: test[:confirmation]
  #     click_on "Sign Up"
  #     assert find('div.alert-success')
  #     alert_message = find('div.alert-success').text
  #     assert_equal('Please check your email to activate your account!', alert_message)
  #   end
  #
  #   tests_invalid_user_not_created.each do |test|
  #     visit signup_path
  #     fill_in "Name", with: test[:name]
  #     fill_in "Email", with: test[:email]
  #     fill_in "Password", with: test[:password]
  #     fill_in "Confirmation", with: test[:confirmation]
  #     click_on "Sign Up"
  #     assert find('div.alert-danger')
  #     alert_message = find('div.alert-danger').text + ': '
  #
  #     error_messages_div = find('#error-explanations', visible: :all)
  #     within(error_messages_div) do
  #       errors = all('li')
  #       errors.each do |error|
  #         alert_message += error.text + ' ,'
  #       end
  #       puts alert_message
  #     end
  #   end
  # end
  #
  # # -----------------------------------------------------------
  #
  # test 'boundary value analisys testing register' do
  #   # boundary values:
  #   # name_1 = name.length = 5, 50
  #   # name_2 = name.length = 4
  #   # name_3 = name.length = 51
  #   #
  #   # email_1 = email.length = 10, 100
  #   # email_2 = email.length = 9
  #   # email_3 = email.length = 99
  #   #
  #   # password_1 = password.length = 8
  #   # password_2 = password.length = 7
  #   tests_valid_user_created = [
  #     {name: 'a' * 5, email: 'a' * 6 + '@b.a', password: 'a' * 8, confirmation: 'a' * 8},
  #     {name: 'a' * 5, email: 'a' * 96 + '@b.a', password: 'a' * 8, confirmation: 'a' * 8},
  #     {name: 'a' * 50, email: 'a' * 6 + '@b.b', password: 'a' * 8, confirmation: 'a' * 8},
  #     {name: 'a' * 50, email: 'a' * 96 + '@b.b', password: 'a' * 8, confirmation: 'a' * 8},
  #   ]
  #   tests_invalid_user_not_created = [
  #     {name:  'a' * 5, email:  'a' * 6 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 5, email:  'a' * 96 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 5, email:  'a' * 5 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 5, email:  'a' * 5 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 5, email:  'a' * 97 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 5, email:  'a' * 97 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 50, email:  'a' * 6 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 50, email:  'a' * 96 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 50, email:  'a' * 5 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 50, email:  'a' * 5 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 50, email:  'a' * 97 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 50, email:  'a' * 97 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 4, email:  'a' * 6 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 4, email:  'a' * 6 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 4, email:  'a' * 96 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 4, email:  'a' * 96 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 4, email:  'a' * 5 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 4, email:  'a' * 5 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 4, email:  'a' * 97 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 4, email:  'a' * 97 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 51, email:  'a' * 6 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 51, email:  'a' * 6 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 51, email:  'a' * 96 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 51, email:  'a' * 96 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 51, email:  'a' * 5 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 51, email:  'a' * 5 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #     {name:  'a' * 51, email:  'a' * 97 + '@a.a', password:  'a' * 8, confirmation:  'a' * 8},
  #     {name:  'a' * 51, email:  'a' * 97 + '@a.a', password:  'a' * 7, confirmation:  'a' * 7},
  #   ]
  #   tests_valid_user_created.each do |test|
  #     visit signup_path
  #     fill_in "Name", with: test[:name]
  #     fill_in "Email", with: test[:email]
  #     fill_in "Password", with: test[:password]
  #     fill_in "Confirmation", with: test[:confirmation]
  #     click_on "Sign Up"
  #     assert find('div.alert-success')
  #     alert_message = find('div.alert-success').text
  #     puts alert_message
  #     assert_equal('Please check your email to activate your account!', alert_message)
  #   end
  #
  #   tests_invalid_user_not_created.each do |test|
  #     visit signup_path
  #     fill_in "Name", with: test[:name]
  #     fill_in "Email", with: test[:email]
  #     fill_in "Password", with: test[:password]
  #     fill_in "Confirmation", with: test[:confirmation]
  #     click_on "Sign Up"
  #     assert find('div.alert-danger')
  #     alert_message = find('div.alert-danger').text + ': '
  #
  #     error_messages_div = find('#error-explanations', visible: :all)
  #     within(error_messages_div) do
  #       errors = all('li')
  #       errors.each do |error|
  #         alert_message += error.text + ' ,'
  #       end
  #       puts alert_message
  #     end
  #   end
  # end
  #
  # # --------------------------------------
  #
  # test 'category partitioning testing register' do
  #   # categories:
  #   # name -> lungime intre [5,50]
  #   # email -> lungime intre [10,100]
  #   # email -> formatare valida
  #   # password -> lungime >= 8
  #   # confirmation -> la fel ca password sau nu
  #   #
  #   # alternatives:
  #   # name:
  #   #   1) name.length < 4
  #   #   2) name.length = 4
  #   #   3) name.length = 5  [ok, lungime_name_5]
  #   #   4) name.length 6..49 [ok, lungime_name_medie]
  #   #   5) name.length = 50 [ok, lungime_name_20]
  #   #   6) name.length = 51
  #   #   7) name.length > 51
  #   #
  #   # email:
  #   #   * 2, ca e o data formatat si o data neformatat
  #   #
  #   #   1) email.length < 9
  #   #   2) email.length = 9
  #   #   3) email.length = 10  [ok, lungime_email_10]
  #   #   4) email.length 11..99 [ok, lungime_email_medie]
  #   #   5) email.length = 100 [ok, lungime_email_20]
  #   #   6) email.length = 101
  #   #   7) email.length > 101
  #   #
  #   # password:
  #   #   1) password.length < 7
  #   #   2) password.length = 7
  #   #   3) password.length = 8 [ok, lungime_password_8]
  #   #   4) password.length > 8 [ok, lungime_password_mare]
  #   #
  #   # confirmation:
  #   #   1) password == confirmation [ok]
  #   #   2) password != confirmation
  #   #
  #   tests_valid_user_created = [
  #     {name: 'a' * 5,email: 'a' * 6 + '@b.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 6 + '@b.b',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 10 + '@b.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 10 + '@b.b',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 96 + '@b.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 96 + '@b.b',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 6 + '@c.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 6 + '@c.c',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 10 + '@c.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 10 + '@c.c',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 96 + '@c.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 96 + '@c.c',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 6 + '@d.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 6 + '@d.d',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 10 + '@d.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 10 + '@d.d',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 96 + '@d.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 96 + '@d.d',password: 'a' * 10,confirmation: 'a' * 10},
  #   ]
  #   tests_invalid_user_not_created = [
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 2,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 4,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 5,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 22,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 50,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 51,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 2 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 5 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 6 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 10 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 96 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 97 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 101 + '@a.a',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 2 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 6 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 7 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 10 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 97 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 98 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 3,confirmation: 'a' * 3 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 7,confirmation: 'a' * 7 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 8,confirmation: 'a' * 8 + 'a'},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10},
  #     {name: 'a' * 55,email: 'a' * 101 + '@aa',password: 'a' * 10,confirmation: 'a' * 10 + 'a'},
  #   ]
  #
  #   tests_valid_user_created.each do |test|
  #     visit signup_path
  #     fill_in "Name", with: test[:name]
  #     fill_in "Email", with: test[:email]
  #     fill_in "Password", with: test[:password]
  #     fill_in "Confirmation", with: test[:confirmation]
  #     click_on "Sign Up"
  #     assert find('div.alert-success')
  #     alert_message = find('div.alert-success').text
  #     assert_equal('Please check your email to activate your account!', alert_message)
  #   end
  #
  #   file = File.open('bad_test_results.txt', 'w')
  #   tests_invalid_user_not_created.each_with_index do |test, index|
  #     visit signup_path
  #     fill_in "Name", with: test[:name]
  #     fill_in "Email", with: test[:email]
  #     fill_in "Password", with: test[:password]
  #     fill_in "Confirmation", with: test[:confirmation]
  #     click_on "Sign Up"
  #
  #     puts index
  #     assert find('div.alert-danger')
  #     alert_message = find('div.alert-danger').text + ': '
  #
  #     error_messages_div = find('#error-explanations', visible: :all)
  #     within(error_messages_div) do
  #       errors = all('li')
  #       errors.each do |error|
  #         alert_message += error.text + ', '
  #       end
  #       file.write(alert_message + "\n")
  #       # puts alert_message
  #     end
  #   end
  #   file.close
  # end
end
